[package]
name = "fuguex-hooks"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"
dyn-clone = "1"
fugue = { version = "0.1", registry = "fugue" }
fuguex-state = { path = "../fuguex-state", version = "0.1", registry = "fugue" }
thiserror = "1"
