[package]
name = "fugue-state-derive"
version = "0.1.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
itertools = "0.10"
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }
quote = "1"
